[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pigeon_solana = "GtJQXa6CQ4qX4GuM92v7DbissAbVwrQJVcx5a4YESiCS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "npx ts-node scripts/initialize.ts"
mint = "npx ts-node scripts/mint.ts"
