[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pigeon_solana = "HqXLvkNCHTvP8RBoYWKe3vKBZbPxrcDseugopMs9bTrG"

[programs.devnet]
pigeon_solana = "HqXLvkNCHTvP8RBoYWKe3vKBZbPxrcDseugopMs9bTrG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/key2.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "npx ts-node scripts/initialize.ts"
setdata = "npx ts-node scripts/setdata.ts"
mint = "npx ts-node scripts/mint.ts"
battle = "npx ts-node scripts/battle.ts"
upgrade = "npx ts-node scripts/upgrade.ts"
purchaseItem = "npx ts-node scripts/purchaseItem.ts"
