[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pigeon_solana = "GtJQXa6CQ4qX4GuM92v7DbissAbVwrQJVcx5a4YESiCS"

[programs.devnet]
pigeon_solana = "GtJQXa6CQ4qX4GuM92v7DbissAbVwrQJVcx5a4YESiCS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "npx ts-node scripts/initialize.ts"
setdata = "npx ts-node scripts/setdata.ts"
mint = "npx ts-node scripts/mint.ts"
battle = "npx ts-node scripts/battle.ts"
